// Generated by https://quicktype.io

import { Address } from 'src/app/types/address.interface';
import { SharedProperty } from 'src/app/types/shared-property.interface';

export interface Residance {
  typeEnum: string;
  label: string;
  createdAt: Date;
  updatedAt: Date;
  type: SharedProperty;
  address?: Address
}
